### ISSUE TITLE
Organize navigation components and view

### ISSUE THREAD

**Issue by andyAndyA** [andyAndyA/Hillfort-Explorer#14]
I want to: Organize the navigation docker with the correct component and view names

So that: I can easily test different activities correctly via navigation through the docker

**Comment by andyAndyA** [comment]
Navigation docker should have the following components:
* Home
   * Un-sortable static list of Hillforts for now
   * Options for creating and deleting personally created Hillforts
* Map
   * Markers with all Hillforts around Google Maps
* Settings
    * Change password and account statistics
* Logout

**Comment by wwongandy** [comment]
Done in branch for #28
